### ISSUE TITLE
Need API & Token

### ISSUE THREAD

**Issue by Asdfuiop** [JohNan/homeassistant-wellbeing#113]
Hi, 

Recently Wellbeing stopped working. 
I have looked at other threads with same problem but I do not understand how to retrieve this newly acquired API and Token. 
There was a link in on thread: https://account.electrolux.one/ui/edp/login?client_id=HeiOpenApi&redirect_uri=https://developer.electrolux.one/loggedin but I cannot login with my credentials there, it says “Something went wrong” when inputting the correct password. 
Am I on the right track?
Am I doing anything wrong? 
Is this a Electrolux problem or a HA wellbeing problem? 

I’m kind of new user on HA and only used the HACS integration, no yaml.

**Comment by ElectricWeasel** [comment]
Hi!
I had the same problem - solved by logging out from Electrolux app on mobile and login again, thne accept T&C. After that i can login into developer portal for API keys and tokens.

Regards
Rafał

**Comment by Asdfuiop** [comment]
🤯
Problem solved, thank you so much!

**Comment by Asdfuiop** [comment]
On to the next problem. 
I installed this but I did not check if the installation actually worked (had other stuff to do). 
Yesterday I noticed that the product was unavailable. 
I did a new installation with new API and Token then restarted HA. But the product is still unavailable even though it has been found by HA.
Any suggestions?
