### ISSUE TITLE
Unable to install package pyelectroluxgroup==0.2.0

### ISSUE THREAD

**Issue by semihselcuk** [JohNan/homeassistant-wellbeing#114]
Hi Everyone, 

I've recently updated the app through HACS but since then I am getting below error. I tried re-installing but no luck. 
I am getting below error: 

Unable to install package pyelectroluxgroup==0.2.0: ERROR: Cannot install pyelectroluxgroup==0.2.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by JohNan** [comment]
Try the latest version 1.2.3 It should support older versions of HA
