### ISSUE TITLE
ULTIMATEHome 500 There are some errors in the mode operation.

### ISSUE THREAD

**Issue by Marxxu3ru** [JohNan/homeassistant-wellbeing#119]
There are currently some errors. When running in Auto mode, there is no action. When running in Manual mode and selecting low-speed mode, an error occurs. I have attached the file. Thank you.

My device only has Smart Mode and Manual Mode, and in Manual Mode, there are five levels of fan speed.

Model Number:EP53-48SWA

[home-assistant_2024-08-16T13-12-39.042Z.log](https://github.com/user-attachments/files/16637546/home-assistant_2024-08-16T13-12-39.042Z.log)

**Comment by JohNan** [comment]
> There are currently some errors. When running in Auto mode, there is no action. When running in Manual mode and selecting low-speed mode, an error occurs. I have attached the file. Thank you.
> 
> My device only has Smart Mode and Manual Mode, and in Manual Mode, there are five levels of fan speed.
> 
> [home-assistant_2024-08-16T13-12-39.042Z.log](https://github.com/user-attachments/files/16637546/home-assistant_2024-08-16T13-12-39.042Z.log)
> 

Thank you. The log file helps me a lot. I'll look into it.
