### ISSUE TITLE
Auth failed....

### ISSUE THREAD

**Issue by Biyadh00** [JohNan/homeassistant-wellbeing#121]
Logger: custom_components.wellbeing
Source: custom_components/wellbeing/config_flow.py:50
integration: Electrolux Wellbeing ([documentation](https://github.com/JohNan/homeassistant-wellbeing), [issues](https://github.com/JohNan/homeassistant-wellbeing/issues))
First occurred: 08:06:14 (2 occurrences)
Last logged: 08:08:10

Validating credentials failed - 429, message='', url='https://api.developer.electrolux.one/api/v1/appliances'

Core
2024.8.2
Supervisor
2024.08.0
Operating System
13.0
Frontend
20240809.0

**Comment by JohNan** [comment]
Too many requests. Try increasing the update interval through the confirmation of the integration.

**Comment by Uffe78** [comment]
Ok how high? 70 sec?

**Comment by Danny-Cap** [comment]
> Ok how high? 70 sec?

https://developer.electrolux.one/documentation/quotasAndRateLimits

It says 5000 calls per day for a free user.. This would be 1 per 18 seconds, but we reach the limit with 30 seconds interval?

I put it to 60 now and hope it will be enough

**Comment by Biyadh00** [comment]
> Too many requests. Try increasing the update interval through the confirmation of the integration.

Perfect, thank you.
