### ISSUE TITLE
Problem getting a Token

### ISSUE THREAD

**Issue by djtail** [JohNan/homeassistant-wellbeing#123]
Im trying to setup the integration, but fails at getting the token and api key

When trying to login at "https://developer.electrolux.one/" i get this error message "Something went wrong"

the mail and password is correct, so i guess the problem are at Electrolux. any workaround for this?

**Comment by Biyadh00** [comment]
Try empty browser cache or open an incognito window.

**Comment by djtail** [comment]
> Try empty browser cache or open an incognito window.

Just tried that, but don't work

![bild](https://github.com/user-attachments/assets/6640a4e4-8d0c-4c1b-ac25-10e1b7240cbd)

**Comment by dinasty02091994** [comment]
I had this problem as well. I signed out from the app and signed in again. 
after that it worked accessing https://developer.electrolux.one/ in a browser.

**Comment by djtail** [comment]
> I had this problem as well. I signed out from the app and signed in again. after that it worked accessing https://developer.electrolux.one/ in a browser.

Thx, That did it
