### ISSUE TITLE
Integration not working Electrolux Well A5

### ISSUE THREAD

**Issue by dam57950** [JohNan/homeassistant-wellbeing#125]
I tried to connect my Electrolux Well A5 but cannot get it working, even witch everything configured, I don't know what to do anymore, thanks for the integration

![Capture d'écran 20 08 2024 à 20 20 34 PM](https://github.com/user-attachments/assets/51bd85fe-9629-4d35-8aae-7991488a53d5)
__________________________________________________________
![Capture d'écran 20 08 2024 à 20 28 58 PM](https://github.com/user-attachments/assets/fa254d1a-5e4b-4e70-ae0d-967655a024f6)
__________________________________________________________
![Capture d'écran 20 08 2024 à 20 21 34 PM](https://github.com/user-attachments/assets/962ad6ae-3a7c-4a95-bc69-2f28ee53592e)
__________________________________________________________
![Capture d'écran 20 08 2024 à 20 21 58 PM](https://github.com/user-attachments/assets/d55881f5-4d82-43c2-917a-4b78a84a822a)
__________________________________________________________
![Capture d'écran 20 08 2024 à 20 27 57 PM](https://github.com/user-attachments/assets/81adabf8-fc51-4f22-8097-b4224d114004)

**Comment by JohNan** [comment]
You need to update Home Assistant to 2024.8 at the moment. I will make it backwards compatible but it's not right now.

**Comment by dam57950** [comment]
Thank you, that was the issue, I now just have an error message (but it works anyway) when I start up the fan

Échec de l'exécution de l'action fan/turn_on. 406, message='Not Acceptable', url='https://api.developer.electrolux.one/api/v1/appliances/950011555105013065087076/command'

**Comment by dam57950** [comment]
And without changing anything, it's not working anymore with error 500 and 429
![Capture d'écran 21 08 2024 à 18 56 56 PM](https://github.com/user-attachments/assets/6cd81d4e-c06d-4a7b-ad12-d6e18f8be5bf)

**Comment by dam57950** [comment]
And without changing anything, it's not working anymore with error 500 and 429
![Capture d'écran 21 08 2024 à 18 56 56 PM](https://github.com/user-attachments/assets/9204dfc0-44c6-4796-8102-a1fbccf4fb50)
