### ISSUE TITLE
"Pure i9 is not a valid model"

### ISSUE THREAD

**Issue by magdogg** [JohNan/homeassistant-wellbeing#137]
Hello

I had this working on 1.23 then I upgraded to 1.24 and 1.25 (mistake maybe...) and now the integration doesn't work again. Error message is in the title.

Ideas?
/Magnus

**Comment by JohNan** [comment]
Enable debug logs and post them here and I'll investigate

**Comment by magdogg** [comment]
Ok thanks, I attached it here now. 
[home-assistant_wellbeing_2024-08-24T09-32-45.855Z.log](https://github.com/user-attachments/files/16736079/home-assistant_wellbeing_2024-08-24T09-32-45.855Z.log)

**Comment by JohNan** [comment]
@magdogg

I realized that there has been some misunderstanding regarding that model. What I can tell PUREi9 is a robot vacuum cleaner, which this integration not support at the moment. Only air purifiers are supported. Correct me if I'm wrong here 😊

**Comment by magdogg** [comment]
@JohNan 
Oh yes that is indeed correct! I do have a Purei9 vacuum but at work, it is connected to my Electrolux account though so maybe that is what is happening. Can you somehow remove it? I should also say this worked for me in 1.23 and this error message came with 1.24-1.26.

**Comment by JohNan** [comment]
> @JohNan 
> Oh yes that is indeed correct! I do have a Purei9 vacuum but at work, it is connected to my Electrolux account though so maybe that is what is happening. Can you somehow remove it? I should also say this worked for me in 1.23 and this error message came with 1.24-1.26.

I have found the issue. I'll publish a new version soon.

**Comment by magdogg** [comment]
@JohNan Tack som fan!

**Comment by danielmorvay** [comment]
I have a similar issue with my robot vacuum cleaner.
It says: 'Gordias' is not a valid Model.
