### ISSUE TITLE
Failed setup, will retry: 500

### ISSUE THREAD

**Issue by Bonanzameh** [JohNan/homeassistant-wellbeing#143]
Hello, 

Device is an AEG AX-91.
Since Sunday (2 days ago) after a reboot (am not quite sure if the reboot was the cause though as I hadn't checked for hours after reboot if it worked or not), I get the following error on the integration page: 
**Failed setup, will retry: 500, message:'Internal Server Error', 
url:"https://api.developer.electrolux.one/api/v1/appliances/(a long number)/info"**

I've updated to the latest version. 1.2.7
I tried reinstalling the integration and downgrading to the last known working version 1.2.6 which results in the same error. 
(btw, version on the integrations page always notes v0.0.0)

I'm not sure if it's server side. 
Is there any way we can read the data locally from the device? The api seems to be quite error sensitive.

Please let me know what I can do to help.

**Comment by patrikjohansson87** [comment]
Also having the same issue

**Comment by magdogg** [comment]
Yea same, their API seems to suck.

**Comment by Bonanzameh** [comment]
Just want to confirm the issue seems to have resolved itself about 1h40m ago.  I'll close this ticket to reduce clutter here.
