### ISSUE TITLE
API rate limit, how to keep it down? (API returns HTTP status code 429)

### ISSUE THREAD

**Issue by AndersRipa** [JohNan/homeassistant-wellbeing#144]
On the API developers page [(https://developer.electrolux.one/documentation/quotasAndRateLimits)]  it states 
**Understanding rate limits**
Rate limits are applied based on a combination of three factors:
- API key: each API key has its own associated rate limit.
- Time window: the limits are measured over a specific period.
- Concurrency: concurrent calls are limited. For example, with the Free plan, you can make a maximum of 5 concurrent calls. 

With the values
- 10 calls/second
- 5 concurrent calls
- 5000 calls/day

**When this is exceeded the API returns HTTP status code 429.
This happens daily for me.**
Is there a way to limit/throttle the amount of calls and if so how do I set it?

**Thank you for a very nice Wellbeing integration, work very much appreciated!**

**Comment by AndersRipa** [comment]
After finding the setting for it in the Integration configuration "API update interval (seconds)" and changed it to 240 from the initial value of 60. Now it works without interruption. (For your information I have 2 air cleaners. )

**Comment by AndersRipa** [comment]
Thank you for the integration!

**Comment by Knigge** [comment]
Thanks for keeping this updated and working!
