### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by Asdfuiop** [JohNan/homeassistant-wellbeing#147]
The integration has not worked great the last couple of months but now I cannot authorize a new connection. 

The integration was unavailable and could not be updated. Therefor I removed the configuration and tried to do a new one. Even with a new API key, Tokken and refresh token it does not work. 
Any suggestions?

![Wellbeing](https://github.com/user-attachments/assets/94c70e05-69f2-492e-a786-7d34b6ee1927)

**Comment by Hondzig** [comment]
The same for me since yesterday. I tried reinstall the integration itself and create new API key with tokens, without success. But thanks @JohNan for great work and all the effort with the integration!

**Comment by JohNan** [comment]
Try to change the update interval. You can do it by clicking Configure on the integration.

**Comment by Asdfuiop** [comment]
Hi JohNan, 

The integration is not installed at the moment. I'm trying to reinstall the connection with my API and new Tokken but it won't accept my API and Tokken.

**Comment by Hondzig** [comment]
Because I tried to reinstall the integration and I can't login, even with a new API key, I can't change anything in the settings... 
![image](https://github.com/user-attachments/assets/8b773201-ec26-4f00-910e-fe8cc0d7fb89)

**Comment by Hondzig** [comment]
I tried a few things today and I was able to login. When I pasted both tokens to the fields and displayed them through the eye icon on the right = the tokens wasn't just dots, but visible symbols. Then it logged me in instantly and integration is working.

**Comment by Asdfuiop** [comment]
After new update I was able to login, Thank you for your hard work!
