### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by OldShaterhan** [JohNan/homeassistant-wellbeing#18]
Hi,
I added integration to the HACS and then to HA, but unfortunately it looks like it is unable to connect with Wellbeing:
```
Logger: homeassistant.config_entries
Source: config_entries.py:324
First occurred: 10:08:02 (2 occurrences)
Last logged: 10:08:40

Config entry '<email>' for wellbeing integration not ready yet; Retrying in background
```

Generally no more logs is found within HA.

![image](https://user-images.githubusercontent.com/1622866/131702786-8df5677c-664c-4bbd-af51-dfbb51aecb0e.png)
Message says: Trying to reconfigure (or similar).

Could you help somehow to fix this issue?
I'm sure email and password given are provided correctly (I was adding integration twice and password was both reentered and copied).

**Comment by OldShaterhan** [comment]
@JohNan are you able to help? ;)

**Comment by OldShaterhan** [comment]
I was properly logged for few days, but integration again failed :(

**Comment by labaland** [comment]
> Without more details from the log it is difficult to say what happened. My guess is that it is probably due to connection issue to the cloud servers.

i have this issue for 2 days now. 

2021-12-21 12:34:57 ERROR (MainThread) [custom_components.wellbeing] Timeout error fetching information from https://electrolux-wellbeing-client.vercel.app/api/m************* -
2021-12-21 12:34:57 ERROR (MainThread) [custom_components.wellbeing] Could not log in to WellBeing, argument of type 'NoneType' is not iterable

**Comment by labaland** [comment]
> Without more details from the log it is difficult to say what happened. My guess is that it is probably due to connection issue to the cloud servers.

works after ha rester but hours/days later i get:
```
Logger: custom_components.wellbeing
Source: custom_components/wellbeing/api.py:412
Integration: Wellbeing ([documentation](https://github.com/JohNan/homeassistant-wellbeing), [issues](https://github.com/JohNan/homeassistant-wellbeing/issues))
First occurred: 18 februari 2022 07:41:27 (1 occurrences)
Last logged: 18 februari 2022 07:41:27

Timeout error fetching information from https://electrolux-wellbeing-client.vercel.app/api/mu52****** -
```

**Comment by labaland** [comment]
> Without more details from the log it is difficult to say what happened. My guess is that it is probably due to connection issue to the cloud servers.

Jag har problemet nästan konstant (otillgänglig). 
 Funkar ibland efter ha restart ett tag. Får inte du det? Kan jag skicka nå loggar och hur isf? A9 pure har jag.

**Comment by JohNan** [comment]
Jo, det blir ofta fel, men det brukar ordna upp sig avsig själv efter ett litet tag.

**Comment by labaland** [comment]
konstant nästan vill jag säga :( har API inställd på 75. ändrade till 90 nu. vad har du där?  skulle vilja göra automationer.. Finns de nån annan väg att göra de? 
![image](https://user-images.githubusercontent.com/20958435/164389713-b38697e8-095f-4418-8c30-0ef2fabc873b.png)

**Comment by OldShaterhan** [comment]
@JohNan does app change changes something in access? After restart I get timeouts now, but when I entry URL from log - I get access token in form of JSON

**Comment by ccxex29** [comment]
I encounter this problem every restart too. For now, my workaround is by disabling and reenabling it after its failure upon restart.

**Comment by JohNan** [comment]
If this is still an issue, please reopen the issue.
