### ISSUE TITLE
Entity naming improvement

### ISSUE THREAD

**Issue by lazyoldbear** [JohNan/homeassistant-wellbeing#25]
Right now, entities are named as `{DEFAULT_NAME}_{self.entity_attr}` which yields numbered outcome if several appliances are present:

- `sensor.wellbeing_temp`
- `sensor.wellbeing_temp_2`

This is extremely inconvenient: sensors are just useless in HA. 
Of course, it is possible to manually rename them all, but that is hardly a sustainable approach. 
The following would be a great (and not very difficult) improvement:

1. Utilise appliance name in entities names.
2. Allow configurable prefix for integration.

**Comment by JohNan** [comment]
@lazyoldbear I changed the name generation in the latest update. Have you tried it out? Let me know how it goes and if all is well we can close this issue.

**Comment by lazyoldbear** [comment]
Entity names are unchanged. Should I remove everything first?

**Comment by JohNan** [comment]
Unfortunately not. I was not able to find a good migration path.

**Comment by lazyoldbear** [comment]
- Removal from UI not possible (2022.4.3)
- Removed manually from .storage/core.entity_registry
- Restarted HA from the menu
- All good

**Comment by lazyoldbear** [comment]
Works. 
Much, much better now. 
The only thing to wish is to use better auth mechanism, but I suppose that is not up to you. 

Thanks a lot!

**Comment by lazyoldbear** [comment]
Fixed at least in 1.0.1 (possibly earlier).
