### ISSUE TITLE
Electrolux well A7 not working

### ISSUE THREAD

**Issue by juraj7396** [JohNan/homeassistant-wellbeing#30]
Firstly I bought Electrolux WELL A7 and tried this integration. After successful installation and log in I got error message - Retrying setup

Logger: homeassistant.config_entries
Source: config_entries.py:366
First occurred: 19:51:40 (3 occurrences)
Last logged: 19:58:39

Config entry ‘XXX’ for wellbeing integration not ready yet; Retrying in background

After that I tried Electrolux Pure A9 and device works perfectly with HomeAssistant. After all when I added to my wellbeing account already mentioned Well A7 and previously there was perfectly working Pure A9, it crashed and also Pure A9 stop working.

There must be some integration problem with Well A7, product number code 95001156, niu firmware version 1.29.0 and mcu firmware version VM174_A_01.03.0.

**Comment by JohNan** [comment]
I don't have a Well A7 myself, so it's kind of hard to debug it.

Try enable debug logging for this integration and let me know the output.

It should be something like

```yaml
logger:
    default: info
    logs:
        custom_components​.​wellbeing​.​api: debug
```

**Comment by juraj7396** [comment]
> I don't have a Well A7 myself, so it's kind of hard to debug it.
> 
> 
> 
> Try enable debug logging for this integration and let me know the output.
> 
> 
> 
> It should be something like
> 
> 
> 
> ```yaml
> 
> logger:
> 
>     default: info
> 
>     logs:
> 
>         custom_components​.​wellbeing​.​api: debug
> 
> ```

I understand, but after I start logger there was only one warning which I already mentioned: 

2022-05-04 22:40:46 WARNING (MainThread) [homeassistant.config_entries] Config entry 'xxx' for wellbeing integration not ready yet; Retrying in background

**Comment by juraj7396** [comment]
So now I see these errors:

This error originated from a custom integration.

Logger: custom_components.wellbeing
Source: custom_components/wellbeing/api.py:427 
Integration: Electrolux Wellbeing (documentation, issues) 
First occurred: 12:02:30 AM (1 occurrences) 
Last logged: 12:02:30 AM

Error fetching information from https://electrolux-wellbeing-client.vercel.app/api/mu52m5PR9X - Cannot connect to host electrolux-wellbeing-client.vercel.app:443 ssl:default [Try again]

This error originated from a custom integration.

Logger: custom_components.wellbeing
Source: custom_components/wellbeing/__init__.py:82 
Integration: Electrolux Wellbeing (documentation, issues) 
First occurred: 12:02:30 AM (1 occurrences) 
Last logged: 12:02:30 AM

Could not log in to WellBeing, argument of type 'NoneType' is not iterable

**Comment by adwiciak** [comment]
Have the same issue with Well A7. Any progress on the issue?

**Comment by JohNan** [comment]
If this is still an issue, please reopen the issue.

**Comment by oleueberolsen** [comment]
I am not sure how to reopen this issue. 
I just go this error this morning after I reloaded the integration. Both my A9 and A7 went offline.

This error originated from a custom integration.

Logger: custom_components.wellbeing
Source: helpers/update_coordinator.py:204
Integration: Electrolux Wellbeing (documentation, issues)
First occurred: June 20, 2023 at 10:01:29 PM (2 occurrences)
Last logged: 9:15:39 AM

Error fetching wellbeing data:

This error originated from a custom integration.

Logger: custom_components.wellbeing
Source: custom_components/wellbeing/api.py:363
Integration: Electrolux Wellbeing (documentation, issues)
First occurred: June 20, 2023 at 10:01:29 PM (1 occurrences)
Last logged: June 20, 2023 at 10:01:29 PM

Timeout error fetching information from https://api.delta.electrolux.com/api/Appliances/950011557103004825087076 -
