### ISSUE TITLE
Electrolux Well A5 compatibility

### ISSUE THREAD

**Issue by Skitcher** [JohNan/homeassistant-wellbeing#32]
First of all, thank you for your this integration! Adding the Well A5 (AX51-304WT) initially gave a fan speed error and the fan couldn't be controlled.  Updating api.py as follows allowed for proper fan control and speed readout:

    @property
    def speed_range(self) -> tuple:
        if self.model == "WELLA7":
            return 1, 5
        if self.model == "PUREA9":
            return 1, 9
        if self.model == "WELLA5":
            return 1, 5

        return 0, 0

Following values are available and seem to be updating well. I only haven't seen a change in the "Status" sensor. 

![image](https://user-images.githubusercontent.com/9772397/166744588-fb0d9351-526b-4fd8-adec-1c03283618a0.png)

**Comment by JohNan** [comment]
Thank you @Skitcher

A new release should be available any minute now.
