### ISSUE TITLE
Add-on doesn't ask for credentials

### ISSUE THREAD

**Issue by Peltiloota** [JohNan/homeassistant-wellbeing#34]
After installation using the recommended HACS method, it never asks for the username and password. Once installed, it says it's pending for restart. After HASS is restarted, it still doesn't ask for the credentials. 
According to installation guide, it seems it should ask them automatically. There's also no indication where I could manually enter them? 

Kindly help whether this is a technical or issue about unclear documentation. 

![Wellbeing](https://user-images.githubusercontent.com/106466603/170859646-df3b2e16-bc4c-4415-9b10-3b68b1809e14.png)

**Comment by zniper-one** [comment]
@Peltiloota you need to add it under integrations after it is installed.
