### ISSUE TITLE
Entities beeing unavailable

### ISSUE THREAD

**Issue by FSHelgeland** [JohNan/homeassistant-wellbeing#35]
After latest update on supervisor 2022.11.2 Entities fall in an out. Sometimes they appear but mostly they dont, unless I do a restart of it. I must admit that I am on Core 2022.11.0, due to trouble with the 11.2 core. It could be that this integration will behave more stable when the next supervisor is here, but for know there are som issuses.

**Comment by jaku2019** [comment]
Hello,
I'm not shure, but switching filters to "Electrolux" app and account seems to solve the problem.

**Comment by JohNan** [comment]
If you are still having issue, please reopen this issue.
