### ISSUE TITLE
Fanspeed shows only on and off

### ISSUE THREAD

**Issue by thoompje** [JohNan/homeassistant-wellbeing#50]
Hello,

Question, the fan speed entity is showing only in historical data on and off. Not the percentage. Hopefully someone can fix this? Thanks a lot!

**Comment by MickLesk** [comment]
Is the problem still present?

**Comment by olanystrom** [comment]
It still only show "On" or "Off"
Not percentage of speed.
![image](https://github.com/JohNan/homeassistant-wellbeing/assets/768798/ffedf0fb-1a51-4987-b260-e362827c5e69)

**Comment by Kaaremi** [comment]
I am trying to build a small automation that puts the Electrolux Well A7 Air Purifier into maximum power (and all the lights on) when the central vacuum cleaner is in operation. When the vacuuming is done I'd like the automation to put the Air Purifier into automatic, i.e. Smart Mode. 

Both the manual Fan speed 1-5 setting and selection of Smart / Manual mode are available in the Air Purifier's own Android app, but not in the HACS integration. The only Action I can see is "Turn on Fan Speed" and even that doesn't seem to increase the fan speed. 

Any chance to see this functionality in the next version?

**Comment by androidand** [comment]
Did you guys try to click on the text "fan speed"? That should open a new window where you can change from auto to manual and set the fan speed in %.

**Comment by thoompje** [comment]
> Did you guys try to click on the text "fan speed"? That should open a new window where you can change from auto to manual and set the fan speed in %.

Hi, I see indeed. That is looking new, many thanks! I'll close the issue now, this is a solution 👍👍
