### ISSUE TITLE
Cannot login anymore

### ISSUE THREAD

**Issue by RiANOl** [JohNan/homeassistant-wellbeing#53]
Few hours ago, the integration stopped working.
I tried to delete it and add it again but always got "Username/Password is wrong."
I can assure username & password correctness since I use them to login app afterwards.
But the Login API response told a different story.
```
{
    "code": 400000,
    "codeDescription": "BadRequest: Undefined.",
    "information": "Failed to login using client Wellbeing",
    "message": ""
}
```
Maybe it caused by API behavior change?

**Comment by yazz007** [comment]
I have the same message, something must changed on API since 21st JUN

**Comment by KjellRanda** [comment]
Same here running Home Assistant 2023.6.2 in a container on a RPI 4

**Comment by olekyd** [comment]
I have the same issue

**Comment by patrikjohansson87** [comment]
![image](https://github.com/JohNan/homeassistant-wellbeing/assets/3233367/3e987c45-34d9-46b3-8d99-23feb0936a0c)

**Comment by indi81** [comment]
I just bought an A9 today and when exploring this HACS I noticed that the wellbeing app is deprecated and cannot be used anymore. They are referring to the new "Electrolux" app instead.

**Comment by FSHelgeland** [comment]
I lost connection yesterday

**Comment by DukeBlackadder** [comment]
Same here. Lost connection 20/6 at 9:15 CET.

**Comment by ZonemanPL** [comment]
Hi, i have the same issue.
[home-assistant_2023-06-23T06-27-17.041Z.log](https://github.com/JohNan/homeassistant-wellbeing/files/11844758/home-assistant_2023-06-23T06-27-17.041Z.log)

**Comment by frank8the9tank** [comment]
Same issue here, removed the integration, added it again, now gives an error that it cannot login.

**Comment by indi81** [comment]
> I just bought an A9 today and when exploring this HACS I noticed that the wellbeing app is deprecated and cannot be used anymore. They are referring to the new "Electrolux" app instead.

Now atleast the Electrolux app started working and I can view and change things. Yesterday it didn't even register nor connect the new A9 in the app.

**Comment by Lampyridae1984** [comment]
Seem to have the same issue. Android app works fine, but integration can't connect to cloud.

**Comment by jdrozdnovak** [comment]
Same. Did they "reddit-out" things? :)

**Comment by modo1302** [comment]
same here with the A9! :(

**Comment by Lampyridae1984** [comment]
Tried to access my A9 remotely today and was apparently logged out of the android app. For some reason my password was no longer valid, so I did a reset. Upon logging in Electrolux sent me a verification code via e-mail. So I'm guessing they have changed the login process and maybe also the API.

**Comment by FSHelgeland** [comment]
The question now is if this is possible to fix, and if johnan will be looking in to it. Would have been nice to have it up running again.

**Comment by JohNan** [comment]
Thank you for all the reports. I'm experience the same problem. 

I'm currently having a hard time due to personal reasons to get time to look at the login issues. 

If someone is willing to give it a shot and push a pull request I'm more than happy to make a quick review and merge if all seems fine.

I'll let you know if I manage to make a fix.

**Comment by jdrozdnovak** [comment]
I think they officially turned off the wellbeing api in favour of the new electrolux app. Atleast the apis looks not to be working. 
@JohNan what was thw approach to read the original api? I can try to do the same with the new app.

**Comment by JohNan** [comment]
That's probably why it doesn't work yes. I think I decompiled the app or used a local vpn on a rooted Android device to read the communication from the app. I honestly doesn't remember exactly 😅

Maybe someone else have implemented the new api as a library that we can use?

**Comment by JohNan** [comment]
I have published a new pre release https://github.com/JohNan/homeassistant-wellbeing/releases/tag/v1.0.6 with the changes from @DarkSession

Thank you for the help!

**Comment by FSHelgeland** [comment]
Will you be adding this to hacs or do we have to update manually?

**Comment by JohNan** [comment]
I have already tried it myself and made it available as the latest version. It should be visible in HACS as version 1.0.6

**Comment by FSHelgeland** [comment]
Fantastisk, himla bra jobbat. Tnx.

**Comment by Lampyridae1984** [comment]
I can confirm as well, 1.0.6 fixes the issue. Great job, thank you very much!

**Comment by Biyadh00** [comment]
Super. Thanx JohNan. Great job!

**Comment by frank8the9tank** [comment]
For me its working again, Thanks!!!!!

**Comment by JohNan** [comment]
Great to hear that it work again! 

A big thank you to @DarkSession who did the fix!
