### ISSUE TITLE
C02 Sensor missing - API update?

### ISSUE THREAD

**Issue by murmlos** [JohNan/homeassistant-wellbeing#58]
Recently updated HA and various addons including Wellbeing. After that the C02 sensor went missing - is it due to being deprecated in the latest API from Wellbeing?

Is there anyway to get it back?

**Comment by MickLesk** [comment]
whats your device? The eCO² Sensor works on my AX7 AEG

**Comment by murmlos** [comment]
Aha!  There was a new entity that I had missed! False alarm! Everything seems to be working with the new entity!
