### ISSUE TITLE
BR: Wrong unit of measurement for sensor.wellbeing_state

### ISSUE THREAD

**Issue by rasssta** [JohNan/homeassistant-wellbeing#6]
First of all, thanks for the new release. Seems to work better on A7 now! :)

I found a minor "typo":

sensor.wellbeing_state has "unit_of_measurement: %"

...which makes it look a bit odd when it says "Smart %" ;)

**Comment by JohNan** [comment]
Thank you!
Fixed in https://github.com/JohNan/homeassistant-wellbeing/releases/tag/v0.0.3
