### ISSUE TITLE
PURE A9

### ISSUE THREAD

**Issue by coserotondo** [JohNan/homeassistant-wellbeing#62]
Hello, is there a way to turn the Ionizer On/Off like the FAN? I can get the status but can operate the Ionizer only from the native App and not from the Integration. Thanks

**Comment by androidand** [comment]
Yes, there is a way. I can have a look at adding this.

**Comment by JohNan** [comment]
Fixed in https://github.com/JohNan/homeassistant-wellbeing/releases/tag/v1.0.10
