### ISSUE TITLE
PURE A9 doesn't change CO2

### ISSUE THREAD

**Issue by hermanops** [JohNan/homeassistant-wellbeing#69]
My CO2 sensor always shows: 549 ppm
The eCO2 shows: 925 ppm and is changing over time.

is there anyway to fix this?

**Comment by ryssel** [comment]
Same here.
I have 2 PURE A9 one off them shows CO2 1.009 all the time the other shows CO2 5.000
eCO2 is changing over time on both.

**Comment by hermanops** [comment]
after I reinstalled, it doesn't show the CO2 sensor, only the eCO2 sensor.

**Comment by ryssel** [comment]
Thanks.
I found this story about estimating C02 level from VOC
https://blog.swegon.com/sv/du-f%C3%A5r-vad-du-m%C3%A4ter-co2-kontra-voc
