### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by amnesia-drop** [JohNan/homeassistant-wellbeing#89]
I keep getting errors that my username/password is incorrect. I can confirm that it is correct since it works fine on Electrolux app and website. Your "documentation" does not provide anything about this!

**Comment by eosban** [comment]
I also encountered this problem while trying to set up an entity with a new Electrolux account just now.

``[custom_components.wellbeing] Error, got error 401 (Unauthorized) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 401, message='Unauthorized', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')``

**Comment by hermanops** [comment]
I'm getting: 
24-02-15 18:58:35.973 ERROR (MainThread) [custom_components.wellbeing] Error, got error 401 (Unauthorized) from server https://api.ocp.electrolux.one/one-account-authorization/api/v1/token - 401, message='Unauthorized', url=URL('https://api.ocp.electrolux.one/one-account-authorization/api/v1/token')
2024-02-15 18:58:35.974 ERROR (MainThread) [custom_components.wellbeing] AccessToken 2 is missing

**Comment by orangesunny** [comment]
Feels like something has changed on the API side 😬 Tried removing and re-downloading different versions of the integration, but no success. Unable to login.

I sent some coffee so your debugging time is more enjoyable, @JohNan. 🤞

**Comment by hermanops** [comment]
Seems to work again

**Comment by orangesunny** [comment]
> Seems to work again

Can confirm. Probably just an API hiccup.

**Comment by nightwissh** [comment]
Looks like I got a new error.
After setup a few hours ago it worked fine so I left it be, then restarted Home Assistant a few times. 
Core 2024.4.3
Supervisor] 2024.04.0
Operating System 12.2
Frontend 20240404.2

using latest v1.0.17
```
2024-04-15 23:44:34.621 ERROR (MainThread) [custom_components.wellbeing] Error, got error 429 () from server https://api.ocp.electrolux.one/one-account-authorization/api/v1/token - 429, message='', url=URL('https://api.ocp.electrolux.one/one-account-authorization/api/v1/token')
2024-04-15 23:44:34.622 ERROR (MainThread) [custom_components.wellbeing] AccessToken 2 is missing
```

**Comment by obs945** [comment]
I encountered same issue as @nightwissh 

2024-04-17 13:39:04.146 ERROR (MainThread) [custom_components.wellbeing] AccessToken 2 is missing
2024-04-17 13:39:06.666 ERROR (MainThread) [custom_components.wellbeing] Error, got error 429 () from server https://api.ocp.electrolux.one/one-account-authorization/api/v1/token - 429, message='', url=URL('https://api.ocp.electrolux.one/one-account-authorization/api/v1/token')

**Comment by thoompje** [comment]
Anyone fixed the issue with the access token message?

**Comment by cod3rk** [comment]
same error, since yesterday i have a 403 forbidden message, and if i try to log in my account, give me an error. I dont know if electrolux block some accounts sometimes

**Comment by dinasty02091994** [comment]
Same thing going on for me as well. seems like they have either changed something on the API side or have some sort of issue. 

ERROR (MainThread) [custom_components.wellbeing] User login failed
ERROR (MainThread) [custom_components.wellbeing] Error, got error 403 (Forbidden) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 403, message='Forbidden', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')

**Comment by cod3rk** [comment]
Start working again, at least from my side, from 12pm CET+2

**Comment by thoompje** [comment]
> Start working again, at least from my side, from 12pm CET+2

Not at my side sadly enough :-(

**Comment by cod3rk** [comment]
> > Start working again, at least from my side, from 12pm CET+2
> 
> Not at my side sadly enough :-(

Failing again since yesterday. It´s clear that they are limiting or whatever per account, maybe number of api calls by time or something....

**Comment by dinasty02091994** [comment]
Quite strange i must say since the app works without any problems while this is going on. those api-calls that the app is making should likely look about the same. Dont have anything to trace the traffic from my phone so i am not sure though.

**Comment by JohNan** [comment]
Try the latest version, it should work now since release 1.2.1

**Comment by thoompje** [comment]
> Try the latest version, it should work now since release 1.2.1

Nice I have download it? Where is the manual to get the api key and tokens? Many thanks in advance!!

**Comment by thoompje** [comment]
> Try the latest version, it should work now since release 1.2.1

Found it sorry🤓✌️ https://github.com/JohNan/homeassistant-wellbeing/releases/tag/v1.2.1
