### ISSUE TITLE
Add Pure 500

### ISSUE THREAD

**Issue by jorgenseike** [JohNan/homeassistant-wellbeing#90]
Hi! Awesome integration, would it be possible to add more information on Pure 500 device? :)  My Pure A9 works amazing, and has fan control, and P.M logging.

**Comment by jorgenseike** [comment]
Started/stopped the debug, and downloaded the file. This is the only line mentioning Welkbeing:

2024-03-13 09:44:33.449 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration wellbeing which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by andrecunha-sb** [comment]
Hello. So I also have this device. Was able to make it work by adding this to fan.py:

```
    def _speed_range(self) -> tuple:
        return self.get_appliance.speed_range[1] if self.get_appliance.speed_range[1] != 0 else (1, 3)

```

The problem with the Pure 500 is that unlike the other models, it supports only 3 modes (by 33% steps). So the default implementation gives a division by zero which can be solved this way. The problem is, this breaks the Pure A9 and the others.

**Comment by andrecunha-sb** [comment]
I have no clue on how to expose the air PM sensor on the Pure 500 though...

**Comment by JohNan** [comment]
@andrecunha-sb do you have a complete response from the api? With that we can probably handle it differently for this model.

**Comment by andrebcunha** [comment]
> @andrecunha-sb do you have a complete response from the api? With that we can probably handle it differently for this model.

@JohNan No. But I cannot do it. Do you have any scripts I can run or do I need to make something on my own?

**Comment by JohNan** [comment]
> > @andrecunha-sb do you have a complete response from the api? With that we can probably handle it differently for this model.
> 
> @JohNan No. But I can do it. Do you have any scripts I can run or do I need to make something on my own?

With the latest release I have added better logging. Add this to your `configuration.yaml`

```yml
logger:
  logs:
    pyelectroluxgroup.appliance: debug
```

Search for `pyelectroluxgroup.appliance` in the logs and post the result here.

**Comment by andrebcunha** [comment]
[wellbeing_log.txt](https://github.com/user-attachments/files/16612594/wellbeing_log.txt)

**Comment by JohNan** [comment]
> @JohNan [wellbeing_log.txt](https://github.com/user-attachments/files/16612594/wellbeing_log.txt)
> 
> Please note that the API access tokens and key are no longer active as of now.

Thank you. What is the model name? You can find it on the device in HA
<img width="354" alt="Screenshot 2024-08-15 at 07 35 49" src="https://github.com/user-attachments/assets/78562091-8e67-47ff-b542-2548f8c6be04">

**Comment by andrebcunha** [comment]
![image](https://github.com/user-attachments/assets/bbf11182-e930-434e-976d-a85c71fdb6a8)

The Pure 500 is known as Muju for some reason. I can tell you some differences: It only supports 3 speeds (hence why fan control is broken and the hack I previously posted works) and it has only a PM1 sensor which I cannot see anywhere. if you need any help just ask.
