### ISSUE TITLE
Integration broken 

### ISSUE THREAD

**Issue by Santaclowns** [JohNan/homeassistant-wellbeing#93]
The problem

unable to log in, integration reports "Username/Password is wrong".

What version of Home Assistant Core has the issue?

Core-2024.5.4

What was the last working version of Home Assistant Core?

No experience, first time user

What type of installation are you running?

Operating System 12.3
Frontend 20240501.1

Integration causing the issue

No response

Link to integration documentation on our website

No response

Diagnostics information

![Screenshot_20240524_121032_Home Assistant.png](https://github.com/JohNan/homeassistant-wellbeing/assets/108698980/64bd36d5-a923-4ad2-aca9-0f8f8f7daa02)

Example YAML snippet

No response

Anything in the logs that might be useful for us?

This error originated from a custom integration.

Logger: custom_components.wellbeing
Source: custom_components/wellbeing/api.py:496
integration: Electrolux Wellbeing (documentation, issues)
First occurred: May 23, 2024 at 10:53:42 PM (4 occurrences)
Last logged: 11:53:26 AM

Error, got error 403 (Forbidden) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 403, message='Forbidden', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')
Error, got error 401 (Unauthorized) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 401, message='Unauthorized', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')

___
This error originated from a custom integration.

Logger: custom_components.wellbeing
Source: custom_components/wellbeing/api.py:373
integration: Electrolux Wellbeing (documentation, issues)
First occurred: May 23, 2024 at 10:53:42 PM (4 occurrences)
Last logged: 11:53:26 AM

User login failed

Additional information

Installed with HACS, following the documentation. 
Setup fails using (correct) credentials registered in official Electrolux Android app

**Comment by runfalk** [comment]
I have the same-ish error.

```
2024-06-05 11:16:35.395 ERROR (MainThread) [custom_components.wellbeing] Error, got error 401 (Unauthorized) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 401, message='Unauthorized', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')
2024-06-05 11:16:35.395 ERROR (MainThread) [custom_components.wellbeing] User login failed
2024-06-05 11:16:47.193 ERROR (MainThread) [custom_components.wellbeing] Error, got error 401 (Unauthorized) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 401, message='Unauthorized', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')
2024-06-05 11:16:47.193 ERROR (MainThread) [custom_components.wellbeing] User login failed
```

**Comment by Crazyhead90** [comment]
I am getting the same issue. Changed the password, am able to login to the AEG wellbeing app, yet the electrolux wellbeing integration tells me the credentials are wrong

**Comment by verhoop** [comment]
+1 for login problems.
Broken, seems like Electrolux has changed something on their end

**Comment by JohNan** [comment]
See this issue https://github.com/JohNan/homeassistant-wellbeing/issues/98

We are working on a solution.
