### ISSUE TITLE
Integration not working anymore

### ISSUE THREAD

**Issue by cpohli** [JohNan/homeassistant-wellbeing#96]
Hi,

since yesterday (31th August 24, around 21:00) the integration fails to setup.
My logs are `showing:

```
Logger: custom_components.wellbeing
Quelle: custom_components/wellbeing/api.py:496
Integration: Electrolux Wellbeing ([Dokumentation](https://github.com/JohNan/homeassistant-wellbeing), [Probleme](https://github.com/JohNan/homeassistant-wellbeing/issues))
Erstmals aufgetreten: 31. Juli 2024 um 19:40:10 (8306 Vorkommnisse)
Zuletzt protokolliert: 16:59:01

Error, got error 403 (Forbidden) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 403, message='Forbidden', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')
Error, got error 502 (Bad Gateway) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 502, message='Bad Gateway', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')
Error, got error 429 () from server https://api.ocp.electrolux.one/one-account-authorization/api/v1/token - 429, message='', url=URL('https://api.ocp.electrolux.one/one-account-authorization/api/v1/token')

```

Any ideas?
Thanks a lot for looking into this.

**Comment by DarkSession** [comment]
I had the same issue.
The problem was that they changed their terms of service and require you to accept them. Try to log out of the Electrolux app, after you log back in you should get the new terms of service. After accepting them this integration should be working again.

**Comment by cpohli** [comment]
Thank you. 
I did as you suggested, but i was not presented with any changes of their TOS (at least here in Germany, if that matters) and had to accept nothing (new).

**Comment by coserotondo** [comment]
Same issue. Accepted new terms from the app but same error for the integration. Tried to reload but same issue. Do I need to restart HA?

**Comment by DarkSession** [comment]
I also had the issue reappear today. Looks like they don't like the `User-Agent: Electrolux/2.9 android/9` header and respond with a 429 too many requests if this header is included.
Removing this header solved it for me. I created a PR:
https://github.com/JohNan/homeassistant-wellbeing/pull/97

Until the PR is approved, you can overwrite the api.py from the PR with the current api.py in the "custom_components/wellbeing" folder.

**Comment by JohNan** [comment]
New version with the fix from @DarkSession has been released.

**Comment by thoompje** [comment]
> New version with the fix from @DarkSession has been released. 

After this "fix" it is still not working. See my logs:

```

2024-08-02 07:07:20.259 ERROR (MainThread) [custom_components.wellbeing] User login failed
2024-08-02 07:07:20.572 ERROR (MainThread) [custom_components.wellbeing] Error, got error 403 (Forbidden) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 403, message='Forbidden', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')
2024-08-02 07:07:20.572 ERROR (MainThread) [custom_components.wellbeing] User login failed
2024-08-02 07:07:20.885 ERROR (MainThread) [custom_components.wellbeing] Error, got error 403 (Forbidden) from server https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate - 403, message='Forbidden', url=URL('https://api.ocp.electrolux.one/one-account-authentication/api/v1/authenticate')
2024-08-02 07:07:20.885 ERROR (MainThread) [custom_components.wellbeing] User login failed

```

**Comment by DarkSession** [comment]
Can you try this to see if you need to accept the new TOS?
https://github.com/JohNan/homeassistant-wellbeing/issues/96#issuecomment-2263383260

**Comment by KrzysztofPlaczek** [comment]
> Can you try this to see if you need to accept the new TOS? [#96 (comment)](https://github.com/JohNan/homeassistant-wellbeing/issues/96#issuecomment-2263383260)

For me was the combination of both things, installing the electrolux app and updating the version. I removed the user agent yesterday as you did in the PR and it did nothing by itself. Anyway v1.0.18 is working fine right now

**Comment by cpohli** [comment]
Thanks! This update worked for me (install and restart HA).
I was not presented with new anything regarding the app - just this update within HA.

**Comment by thoompje** [comment]
Deleted the integration and trying to add my account again. I got the message :Username/Password is wrong.
In the app the username (emailadress) and password are working... Also tried to sign off and sign in again and accept the new terms bur sadly enough still no luck

**Comment by orangesunny** [comment]
> Deleted the integration and trying to add my account again. I got the message :Username/Password is wrong. In the app the username (emailadress) and password are working... Also tried to sign off and sign in again and accept the new terms bur sadly enough still no luck

I am in the same situation. Accepted the new terms thanks to @DarkSession, even removed the integration and add it again. No luck, I get `Username/Password is wrong.` when setting up the 1.0.18 integration.
Credentials work in the official app, I have them in password manager.
