### ISSUE TITLE
V 1.0.8 => login broken

### ISSUE THREAD

**Issue by Alec-99** [JohNan/homeassistant-wellbeing#99]
Just a quick reminder i'll elaborate on this at a later date;

Login suddenly stopped working with my homeassistant, weird stuff happening, didnt had the time to investigate.

Still great kudos to the maintaners, this application has been one of the reasons why i bougt the electrolux 😅

**Comment by noahwilliamsson** [comment]
See the discussion in https://github.com/JohNan/homeassistant-wellbeing/issues/98.  As I understand it, Electrolux has a new public API with a different authentication mechanism.  The old API appears to be rejecting new logins as of last week.

Initial support for the new API has been implemented in https://github.com/JohNan/pyelectroluxgroup.  There's however still work remaining to integrate this project with this newly implemented API client.
